### ISSUE TITLE
Zjednoduseni excludu aktivity monitoringu z detailnich logu

### ISSUE THREAD

**Issue by semik** [CESNET/ansible-freeradius#7]
Diky rewrite_calling_station_id lze zjednodusit vylouceni monitoringu z detailnich logu. Az to zaktualizujes v dokumentaci FR3 na eduroam.cz tak to aplikuj i na tuhle roli.

**Comment by lager1** [comment]
Je to pripraveno v https://github.com/CESNET/ansible-freeradius/pull/11

**Comment by lager1** [comment]
dokumentace na eduroam.cz take aktualizovana.
